name: Build and package
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - abhinai

jobs:
  checking_environment:
    outputs:
      node_version: ${{ steps.node_step.outputs.node_version }}
    name: checking the environment
    runs-on: ubuntu-latest
    steps:
      - name: echoing node version
        run : echo node_version=`node -v` > "$GITHUB_OUTPUT"
        id: node_step
      - name: checking the node version
        run: echo "::notice::${{steps.node_step.outputs.node_version}}"
  code_checkout:
    needs: checking_environment
    if: success()
    name: checking out the code from the repo	  
    runs-on: ubuntu-latest
    steps:
      - name: confirming node version
        run: echo "::notice::${{needs.checking_environment.outputs.node_version}}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          path: '/app'
      - name: listing all the files
        run: |
          cd
          echo "::notice listing all the files::${{steps.node_step.outputs.node_version}}"
      - name: installing dependencies
        run: npm install			  