name: Build and package

on:
  push:
    branches:
      - "abhinai"
  workflow_dispatch:
    

jobs:
  log:
    name: log a message in the console
    runs-on: ubuntu-latest
    steps:
      - name: echoing a message in the console
        run: ls