name: Build and package
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
		branches:
	  	- abhinai

jobs:
  setting_environment:
		name: installing nodev20
		runs-on: ubuntu-latest