name: Build and package
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - "abhinai"
  workflow_dispatch:
    

jobs:
  log:
    name: log a message in the console
    runs-on: ubuntu-latest
    steps:
      - name: echoing a message in the console
        run: |
          mkdir abhinai
          cd abhinai
          touch a.html
      - name : cd into abhinai
        run: |
          cd abhinai
          ls