name: Build and package
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - abhinai

jobs:
  checking_environment:
    name: checking the environment
    runs-on: ubuntu-latest
    steps:
      - name: echoing node version
        run : echo node_version=`node -v` > "$GITHUB_OUTPUT"
        id: node_step
      - name: checking the node version
        run: echo ::debug::${{steps.node_step.outputs.node_version}}

